name: test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i && npm run lint

  unit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            node_modules
            test/e2e/miniprogram-project/node_modules
            test/e2e/plugin-project/node_modules
            test/e2e/miniprogram-wxss-loader/node_modules

          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i && npm i --prefix test/e2e/miniprogram-project && npm i --prefix test/e2e/plugin-project && npm i --prefix test/e2e/miniprogram-wxss-loader && npx lerna bootstrap --no-ci

      - name: copy-webpack-plugin
        run: npm run copyPlugin --prefix test/e2e/miniprogram-project && npm run copyPlugin --prefix test/e2e/plugin-project && npm run copyPlugin --prefix test/e2e/miniprogram-wxss-loader

      - name: build-miniprogram
        run: npm run build:cross --prefix test/e2e/miniprogram-project

      - name: build-plugin
        run: npm run build --prefix test/e2e/plugin-project

      - name: build-wxss-loader
        run: npm run build --prefix test/e2e/miniprogram-wxss-loader

      - name: exec unit test
        run: npm t && npm t --prefix test/e2e/miniprogram-project && npm t --prefix test/e2e/plugin-project && npm t --prefix test/e2e/miniprogram-wxss-loader
